server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    # GCP-Maria(GoogleCloud)
    url: jdbc:mariadb://34.64.143.51:3306/myexer
    username: root
    password: 3111
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback-${spring.profiles.active}.xml      
