spring:
  profiles:
    active: local
  
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    # local-Maria
#    url: jdbc:mariadb://localhost:3306/test
#    username: root
#    password: 1111
#    driver-class-name: org.mariadb.jdbc.Driver
  
    # local-MySql_5.7
#    url: jdbc:mysql://localhost:3307/test?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3307/test?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    # aaronyeom Test
#    url: jdbc:mysql://192.168.0.151:32770/deg
#    username: root
#    password: aaronyeom
#    driver-class-name: com.mysql.cj.jdbc.Driver
    
server:
  port: 9090
  servlet:    encoding:      charset: UTF-8
      enabled: true
      force: true

logging:
  config: classpath:logback-${spring.profiles.active}.xml           
