server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /META-INF/views/
      suffix: .jsp
      
  datasource:
    # local-Maria
#    url: jdbc:mariadb://localhost:3306/myexer
#    username: root
#    password: 3111
#    driver-class-name: org.mariadb.jdbc.Driver

    # GCP-Maria(GoogleCloud)
    url: jdbc:mariadb://34.64.143.51:3306/myexer
    username: root
    password: 3111
    driver-class-name: org.mariadb.jdbc.Driver
  
    # local-MySql_5.7
#    url: jdbc:mysql://localhost:3307/test?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8
#    url: jdbc:mysql://localhost:3307/test?useUnicode=yes&characterEncoding=UTF-8
#    username: root
#    password: 1111
#    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback-${spring.profiles.active}.xml           
