DROP TABLE degcs_data_plan;
CREATE TABLE `degcs_data_plan` (
  `DEGCS_SVCCD` varchar(20) NOT NULL,
  `DEGCS_SVCNM` varchar(100) NOT NULL,
  `DEGCS_ENABLE_YN` varchar(1) NOT NULL,
  `DEGCS_SVC_UPDATEDATE` int NOT NULL,
  `DEGCS_SVC_CREATEDATE` int NOT NULL,
  PRIMARY KEY (`DEGCS_SVCCD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;

INSERT INTO degcs_data_plan
(DEGCS_SVCCD, DEGCS_SVCNM, DEGCS_ENABLE_YN, DEGCS_SVC_UPDATEDATE, DEGCS_SVC_CREATEDATE)
VALUES("LRZ0002100", "5G 데이터무한", "Y", UNIX_TIMESTAMP(), UNIX_TIMESTAMP());

INSERT INTO degcs_data_plan
(DEGCS_SVCCD, DEGCS_SVCNM, DEGCS_ENABLE_YN, DEGCS_SVC_UPDATEDATE, DEGCS_SVC_CREATEDATE)
VALUES("LRZ0001166", "5G 스탠다드 ( 데이터 150GB-요금제 종속)", "Y", UNIX_TIMESTAMP()+1, UNIX_TIMESTAMP()+1);

INSERT INTO degcs_data_plan
(DEGCS_SVCCD, DEGCS_SVCNM, DEGCS_ENABLE_YN, DEGCS_SVC_UPDATEDATE, DEGCS_SVC_CREATEDATE)
VALUES("LRZ0001100", "LTE데이터 Ultimate(요금제종속)", "Y", UNIX_TIMESTAMP()+2, UNIX_TIMESTAMP()+2);

INSERT INTO degcs_data_plan
(DEGCS_SVCCD, DEGCS_SVCNM, DEGCS_ENABLE_YN, DEGCS_SVC_UPDATEDATE, DEGCS_SVC_CREATEDATE)
VALUES("LRZ0001820", "(LTE)청소년 요금제 데이터 일 5GB", "Y", UNIX_TIMESTAMP()+3, UNIX_TIMESTAMP()+3);

INSERT INTO degcs_data_plan
(DEGCS_SVCCD, DEGCS_SVCNM, DEGCS_ENABLE_YN, DEGCS_SVC_UPDATEDATE, DEGCS_SVC_CREATEDATE)
VALUES("LRZ0003814", "LTE데이터 일 5G VAS(요금제 종속, 5Mbps QoS)", "Y", UNIX_TIMESTAMP()+4, UNIX_TIMESTAMP()+4);

INSERT INTO degcs_data_plan
(DEGCS_SVCCD, DEGCS_SVCNM, DEGCS_ENABLE_YN, DEGCS_SVC_UPDATEDATE, DEGCS_SVC_CREATEDATE)
VALUES("LRZ0000425", "5G 태블릿 4GB+데이터 나눠쓰기", "Y", UNIX_TIMESTAMP()+5, UNIX_TIMESTAMP()+5);
